export const ONDC_COLORS = {
  ACCENTCOLOR: "#F37A20",
  BACKGROUNDCOLOR: "#f0f0f0",
  PRIMARYCOLOR: "#1e1e1e",
  SECONDARYCOLOR: "#7b7b7b",
  PLACEHOLDERTEXT: "#bcbcbc",
  ERROR: "#F33636",
  SUCCESS: "#59ff9c",
  WHITE: "#fff",
};
